services:
  # Backend Service (Node.js)
  - type: web
    name: time2cinema-backend
    env: node
    rootDir: ./backend
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: time2cinema_db
          property: connectionString
      - key: NODE_ENV
        value: production

  # Frontend Service (Next.js)
  - type: web
    name: time2cinema-frontend
    env: node
    rootDir: ./frontend
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: time2cinema-backend
          property: url
      - key: NODE_ENV
        value: production
