name: Hourly ATMovies Data Update Check (5/18 Only)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # 5月18日 03:15-09:15（台灣時間）每小時執行一次
    # 注意：GitHub Actions 使用 UTC 時間，所以是 5月17日 19:15 到 5月18日 01:15
    - cron: '15 19,20,21,22,23,0,1 17,18 5 *'  # 5月17-18日，只在指定時間執行

jobs:
  check_atmovies_data_update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 aiohttp
      
      - name: Run ATMovies Data Update Checker
        env:
          MAX_THEATERS_TO_CHECK: "10" # Environment variable for the script
          TZ: Asia/Taipei # Set timezone for logging purposes within the script if it uses system time
        run: |
          echo "Running ATMovies Data Update Checker..."
          python scripts/scrapers/atmovies_data_update_checker.py
          echo "ATMovies Data Update Checker finished."
